server:
  port: 10010
#  servlet:
#    context-path: /helei

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: 962464HeLei
    jdbcUrl: jdbc:mysql://localhost:3306/retinal_segmentation?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  redis:
    host: 81.68.94.6
    port: 6379
    Auth: 962464
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
  rabbitmq:
    host: 81.68.94.6 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual


  mail:
    host: smtp.qq.com
    username: 914577981@qq.com
    password: vmilliwecqzdbfeb
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.helei.retinalsegmentation.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1


logging:
  level:
    org.helei.retinalsegmentation: debug

helei:
  script:
    location: /Users/helei/develop/ideaworkspace/RetinalSegmentation/src/main/resources/static/plus.py
    appendFile: /Users/helei/develop/ideaworkspace/RetinalSegmentation/src/main/resources/static/test.txt
    maskFile: /Users/helei/develop/ideaworkspace/RetinalSegmentation/src/main/resources/static/Image_Mask.png
    pythonLct: D:\anoconda\python.exe
