server:
  port: 10010
#  servlet:
#    context-path: /helei

spring:

  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: 962464HeLei
    jdbcUrl: jdbc:mysql://localhost:3306/retinal_segmentation?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8

  mail:
    host: smtp.qq.com
    username: 914577981@qq.com
    password: vmilliwecqzdbfeb
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.helei.retinalsegmentation.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    org.helei.retinalsegmentation: debug
